#!/usr/bin/python
# -*- coding: UTF-8 -*-

import sys 
import os 
args = sys.argv[1:]

if len(args) < 1:
    print("\033[31m Error Need Path \033[0m")
    sys.exit(2)

target = args[0]
if not os.path.exists(target):
    os.makedirs(args[0])
cmds = ['cp ./time.limit ' + target,
        'cp ./Program.md ' + target + '/README.md',
        'cp ./*.in ' + target,
        'cp ./*.in.want ' + target,
        'cp ./Main.cpp ' + target,
        ]

for cmd in cmds:
    print(cmd)
    os.system(cmd)
