#!/usr/bin/python
# -*- coding: UTF-8 -*-

import sys 
import os 
args = sys.argv[1:]

if len(args) < 1:
    print("\033[31m Error Need Path \033[0m")
    sys.exit(2)

target = args[0]
cmds = ['mv ./' + target + '/README.md ./' + target + '/Program.md',
        'cp ./' + target + '/* ./',
        'mv ./' + target + '/Program.md ./' + target + '/README.md'

        ]

for cmd in cmds:
    print(cmd)
    os.system(cmd)
